# name of the workflow
name: CICD

on:
  workflow_dispatch:

# Jobs
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Here we are taking code to version control system
        run: echo "git clone or git pull"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Here we are building docker file
        run: echo "docker build"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Here we are in the testing phase
        run: echo "testing has been done"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Here we are deploying the application to AWS
        run: echo "Application has been deployed to AWS"
