#name of the workflow 
name: CICD



on: 
  workflow_dispatch:

#NAME OF THE JOB 
jobs:
    code:
        runs-on: ubuntu-latest
        steps:
            -name : Here we are taking code to version contro system 
            run : echo " git clone or git pull "
    build:
        runs-on: ubuntu-latest
        steps:
               -name : Here we are bulding docker file 
               run : echo " docker build "
    test:
        runs-on: ubuntu-latest
        steps:
              -name : Here we are in the testing phase 
              run : echo " testing has been done "
     deploy:
        runs-on: ubuntu-latest
        steps:
              -name : Here we are deploying the application to aws 
              run : echo " Application has been deployed to AWS"
